### ISSUE TITLE
Friends list call not working

### ISSUE THREAD

**Issue by shauket** [sdkbox-doc/en#134]
Hi,

Friend list call not working,please check it its stop after updaitng new sdkbox sdk.

![screen shot 2016-02-25 at 5 19 05 pm](https://cloud.githubusercontent.com/assets/6191749/13319522/0c0b7486-dbe4-11e5-8c76-4985db6df578.png)

**Comment by darkdukey** [comment]
Thanks for reporting this, we'll look into this.

**Comment by yinjimmy** [comment]
Fixed
