### ISSUE TITLE
Make sure the manual integration section is copy paste ready

### ISSUE THREAD

**Issue by darkdukey** [sdkbox-doc/en#19]
Some sections contains a undesirable ">"

Like this
```
> -force_load AdColony.framework/AdColony
```
If I copy paste it to Xcode, it will cause an error.

**Comment by slackmoehrle** [comment]
> is part of markdown though, as how you make a list.

**Comment by darkdukey** [comment]
http://sdkbox-doc.github.io/en/plugins/adcolony/v3-cpp/#manual-integration-for-ios

**Comment by slackmoehrle** [comment]
This is an indenting issue. Fixing it.
