### ISSUE TITLE
Fyber docs are unclear.

### ISSUE THREAD

**Issue by slackmoehrle** [sdkbox-doc/en#33]
@yinjimmy Fyber docs are unclear. Look at `v3-cpp/usage.md`

1. Section: __#### Rewarded Video__

We are stating to the users: __iOS configure follow__ and __Android configure follow__
Can we really ask them to do this? This doc we link to tells them to download SDK's etc that we don't need to do. Should we tell them to just follow this instead: http://developer.fyber.com/content/ios/basics

2.  This:
Display an available rewarded video, call `requestOffers` first.
```cpp
sdkbox::PluginFyber::showOffers();
```
We are saying call `requestOffers` but showing code for `showOffers()` which is correct?

These items occur in cpp, js and lua docs.

**Comment by slackmoehrle** [comment]
@yinjimmy just looking for an update on this so I can finalize today/tomorrow ahead of the 9/16 release.

**Comment by yinjimmy** [comment]
show offers step:

1. requestOffers()
2. show offers with in delegate `onBrandEngageClientReceiveOffers` callback.

Developer can `requestOffers` anytime, then `showOffers` without any delay.

**Comment by yinjimmy** [comment]
sorry for late..

**Comment by slackmoehrle** [comment]
Thank you Jimmy. I have worked the language and updated the docs.
