### ISSUE TITLE
Soomla docs clarifications

### ISSUE THREAD

**Issue by slackmoehrle** [sdkbox-doc/en#34]
@hugohuang1111 A few things:

I see a file called: soomlagrow iOS.entitlements but we don't mention it in the docs anyplace. Why is this here? when is it used? Does the user need to modify it in anyway?

in `soomlagrow/shared/manual_ios_V3.md`, I dont see where we list other frameworks Soolma Grow requires. We only list `sdkbox.framework` and `PluginSoomlaGrow.framework`. 

Is this really all that is required or are there System Frameworks too?

**Comment by hugohuang1111** [comment]
soomlagrow iOS.entitlements is useless

required fllow system frameworks
    Security.framework
    libsqlite3.0.dylib
    StoreKit.framework
    CFNetwork.framework
    libicucore.dylib
    SystemConfguration.framework
    AdSupport.framework
