### ISSUE TITLE
Formatting issue with Facebook invite documenation

### ISSUE THREAD

**Issue by darkdukey** [sdkbox-doc/en#77]
<img width="985" alt="screen shot 2015-10-15 at 3 58 31 pm" src="https://cloud.githubusercontent.com/assets/371584/10529766/b0733114-7355-11e5-9889-0d4bd571bf17.png">

http://sdkbox-staging.github.io/en/plugins/facebook/v3-js/

**Comment by slackmoehrle** [comment]
one sec, let me fix. Weird, doesn't happen for me in Marked or Atom Preview.

**Comment by slackmoehrle** [comment]
Fixed in PR
